namespace LintSolution1
{
	namespace FindTheMissingNumber_Medium{ void Main(); }
	namespace InvertBinaryTree_Easy{ void Main(); }
	namespace MaxPointsOnALine_Medium{ void Main(); }
	namespace SpaceReplacement_Easy{ void Main(); }
	namespace LongestWords_Easy{ void Main(); }
	namespace CopyBooks_Hard{ void Main(); }
	namespace MaximalSquare_Medium{ void Main(); }
	namespace PostOfficeProblem_Hard{ void Main(); }
	namespace NumberOfIslandsII_Hard{ void Main(); }
	namespace NumberOfIslands_Easy{ void Main(); }
	namespace FindTheWeakConnectedComponentInTheDirectedGraph_Medium{ void Main(); }
	namespace FindTheConnectedComponentInTheUndirectedGraph_Easy{ void Main(); }
	namespace ScrambleString_Hard{ void Main(); }
	namespace NutsAndBoltsProblem_Medium{ void Main(); }
	namespace SubmatrixSum_Medium{ void Main(); }
	namespace ContinuousSubarraySum_Medium{ void Main(); }
	namespace ContinuousSubarraySumII_Medium{ void Main(); }
	namespace EvaluateReversePolishNotation_Medium{ void Main(); }
	namespace ValidParentheses_Easy{ void Main(); }
	namespace LengthOfLastWord_Easy{ void Main(); }
	namespace SimplifyPath_Medium{ void Main(); }
	namespace SubarraySumII_Hard{ void Main(); }
	namespace MaximumGap_Hard{ void Main(); }
	namespace KthSmallestNumberInSortedMatrix_Medium{ void Main(); }
	namespace CountAndSay_Easy{ void Main(); }
	namespace RomanToInteger_Medium{ void Main(); }
	namespace IntegerToRoman_Medium{ void Main(); }
	namespace ValidNumber_Hard{ void Main(); }
	namespace ValidPalindrome_Easy{ void Main(); }
	namespace MinimumSizeSubarraySum_Medium{ void Main(); }
	namespace LongestIncreasingContinuoussubsequence_Easy{ void Main(); }
	namespace LongestIncreasingContinuoussubsequenceII_Hard{ void Main(); }
	namespace PartitionArraybyOddAndEven_Easy{ void Main(); }
	namespace LongestPalindromicSubstring_Medium{ void Main(); }
	namespace NextPermutationII_Medium{ void Main(); }
	namespace MergeIntervals_Easy{ void Main(); }
	namespace CountOneInBinary_Easy{ void Main(); }
	namespace Fibonacci_Easy{ void Main(); }
	namespace DeleteNodeInTheMiddleOfSinglyLinkedList_Easy{ void Main(); }
	namespace Subtree_Easy{ void Main(); }
	namespace CoinsInALineIII_Hard{ void Main(); }
	namespace CoinsInALineII_Medium{ void Main(); }
	namespace CoinsInALine_Medium{ void Main(); }
	namespace BestTimeToBuyAndSellStockIV_Hard{ void Main(); }
	namespace HouseRobber_Medium{ void Main(); }
	namespace Candy_Hard{ void Main(); }
	namespace ReverseInteger_Easy{ void Main(); }
	namespace GrayCode_Medium{ void Main(); }
	namespace DivideTwoIntegers_Medium{ void Main(); }
	namespace PlusOne_Easy{ void Main(); }
	namespace ConvertSortedArrayToBinarySearchTreeWithMinimalHeight_Easy{ void Main(); }
	namespace AddBinary_Easy{ void Main(); }
	namespace TriangleCount_Hard{ void Main(); }
	namespace AssignmentOperatorOverloadingCPlusPlusOnly_Medium{ void Main(); }
	namespace PrintNumbersbyRecursion_Medium{ void Main(); }
	namespace FindPeakElementII_Hard{ void Main(); }
	namespace ContainerWithMostWater_Medium{ void Main(); }
	namespace LongestSubstringWithoutRepeatingCharacters_Medium{ void Main(); }
	namespace NumberOfAirplanesInTheSky_Medium{ void Main(); }
	namespace TheSmallestDifference_Medium{ void Main(); }
	namespace LongestSubstringwithAtMostKDistinctCharacters_Medium{ void Main(); }
	namespace CountOfSmallerNumberbeforeitself_Hard{ void Main(); }
	namespace ValidSudoku_Easy{ void Main(); }
	namespace ExpressionTreeBuild_Hard{ void Main(); }
	namespace ConvertExpressionToReversePolishNotation_Hard{ void Main(); }
	namespace ConvertExpressionToPolishNotation_Hard{ void Main(); }
	namespace BuildingOutline_Hard{ void Main(); }
	namespace CountOfSmallerNumber_Medium{ void Main(); }
	namespace PermutationSequence_Medium{ void Main(); }
	namespace ExpressionEvaluation_Hard{ void Main(); }
	namespace TrappingRainWaterII_Hard{ void Main(); }
	namespace SlidingWindowMedian_Hard{ void Main(); }
	namespace TrappingRainWater_Medium{ void Main(); }
	namespace SlidingWindowMaximum_Hard{ void Main(); }
	namespace FirstMissingPositive_Medium{ void Main(); }
	namespace SegmentTreeQueryII_Medium{ void Main(); }
	namespace IntervalSumII_Hard{ void Main(); }
	namespace IntervalSum_Medium{ void Main(); }
	namespace IntervalMinimumNumber_Medium{ void Main(); }
	namespace Singleton_Easy{ void Main(); }
	namespace SegmentTreeModify_Medium{ void Main(); }
	namespace SegmentTreeQuery_Medium{ void Main(); }
	namespace SegmentTreeBuild_Medium{ void Main(); }
	namespace PermutationIndexII_Medium{ void Main(); }
	namespace PermutationIndex_Easy{ void Main(); }
	namespace WildcardMatching_Hard{ void Main(); }
	namespace MaximumProductSubarray_Medium{ void Main(); }
	namespace GasStation_Medium{ void Main(); }
	namespace MatrixZigzagTraversal_Easy{ void Main(); }
	namespace LargestNumber_Medium{ void Main(); }
	namespace WoodCut_Medium{ void Main(); }
	namespace DeleteDigits_Medium{ void Main(); }
	namespace FlipBits_Easy{ void Main(); }
	namespace BinaryRepresentation_Hard{ void Main(); }
	namespace UpdateBits_Medium{ void Main(); }
	namespace RouteBetweenTwoNodesInGraph_Medium{ void Main(); }
	namespace RemoveNthNodeFromEndOfList_Easy{ void Main(); }
	namespace InsertionSortList_Easy{ void Main(); }
	namespace RemoveElement_Easy{ void Main(); }
	namespace Anagrams_Medium{ void Main(); }
	namespace RotateList_Medium{ void Main(); }
	namespace AddTwoNumbers_Easy{ void Main(); }
	namespace NthToLastNodeInList_Easy{ void Main(); }
	namespace MergeTwoSortedLists_Easy{ void Main(); }
	namespace UniqueBinarySearchTreesII_Medium{ void Main(); }
	namespace UniqueBinarySearchTrees_Medium{ void Main(); }
	namespace SetMatrixZeroes_Medium{ void Main(); }
	namespace RotateImage_Medium{ void Main(); }
	namespace FindMinimumInRotatedSortedArrayII_Medium{ void Main(); }
	namespace FindMinimumInRotatedSortedArray_Medium{ void Main(); }
	namespace TwoStringsAreAnagrams_Easy{ void Main(); }
	namespace UniqueCharacters_Easy{ void Main(); }
	namespace MinimumDepthOfBinaryTree_Easy{ void Main(); }
	namespace RegularExpressionMatching_Hard{ void Main(); }
	namespace CombinationSumII_Medium{ void Main(); }
	namespace Combinations_Medium{ void Main(); }
	namespace BestTimeToBuyAndSellStockIII_Medium{ void Main(); }
	namespace BestTimeToBuyAndSellStockII_Medium{ void Main(); }
	namespace BestTimeToBuyAndSellStock_Medium{ void Main(); }
	namespace SortColors_Medium{ void Main(); }
	namespace InterleavingPositiveAndNegativeNumbers_Medium{ void Main(); }
	namespace SortColorsII_Medium{ void Main(); }
	namespace O1CheckPowerOfTwo_Easy{ void Main(); }
	namespace Sqrtx_Easy{ void Main(); }
	namespace FastPower_Medium{ void Main(); }
	namespace SubarraySumClosest_Medium{ void Main(); }
	namespace SubarraySum_Easy{ void Main(); }
	namespace CloneGraph_Medium{ void Main(); }
	namespace PalindromePartitioning_Easy{ void Main(); }
	namespace CombinationSum_Medium{ void Main(); }
	namespace LRUCache_Hard{ void Main(); }
	namespace WordSearchII_Hard{ void Main(); }
	namespace Heapify_Medium{ void Main(); }
	namespace Rehashing_Medium{ void Main(); }
	namespace HashFunction_Easy{ void Main(); }
	namespace TopologicalSorting_Medium{ void Main(); }
	namespace MaxTree_Hard{ void Main(); }
	namespace BackpackII_Medium{ void Main(); }
	namespace LongestConsecutiveSequence_Medium{ void Main(); }
	namespace WordSearch_Medium{ void Main(); }
	namespace LargestRectangleInHistogram_Hard{ void Main(); }
	namespace WordLadderII_Hard{ void Main(); }
	namespace WordLadder_Medium{ void Main(); }
	namespace EditDistance_Medium{ void Main(); }
	namespace DistinctSubsequences_Medium{ void Main(); }
	namespace JumpGameII_Medium{ void Main(); }
	namespace JumpGame_Medium{ void Main(); }
	namespace UniquePathsII_Easy{ void Main(); }
	namespace UniquePaths_Easy{ void Main(); }
	namespace RemoveDuplicatesfromSortedListII_Medium{ void Main(); }
	namespace RemoveDuplicatesfromSortedList_Easy{ void Main(); }
	namespace ClimbingStairs_Easy{ void Main(); }
	namespace MinimumPathSum_Easy{ void Main(); }
	namespace Triangle_Easy{ void Main(); }
	namespace WordBreak_Medium{ void Main(); }
	namespace PalindromePartitioningII_Medium{ void Main(); }
	namespace ConvertSortedListToBinarySearchTree_Medium{ void Main(); }
	namespace CopyListwithRandomPointer_Medium{ void Main(); }
	namespace MergekSortedLists_Medium{ void Main(); }
	namespace LinkedListCycleII_Hard{ void Main(); }
	namespace LinkedListCycle_Medium{ void Main(); }
	namespace RemoveDuplicatesfromSortedArrayII_Easy{ void Main(); }
	namespace RemoveDuplicatesfromSortedArray_Easy{ void Main(); }
	namespace ReorderList_Medium{ void Main(); }
	namespace SortList_Medium{ void Main(); }
	namespace MaximumDepthOfBinaryTree_Easy{ void Main(); }
	namespace PartitionList_Easy{ void Main(); }
	namespace ValidateBinarySearchTree_Medium{ void Main(); }
	namespace BinaryTreeMaximumPathSum_Medium{ void Main(); }
	namespace BalancedBinaryTree_Medium{ void Main(); }
	namespace Backpack_Medium{ void Main(); }
	namespace MinimumAdjustmentCost_Medium{ void Main(); }
	namespace kSumII_Medium{ void Main(); }
	namespace kSum_Hard{ void Main(); }
	namespace LowestCommonAncestor_Medium{ void Main(); }
	namespace RemoveNodeInBinarySearchTree_Hard{ void Main(); }
	namespace BinarySearchTreeIterator_Hard{ void Main(); }
	namespace InsertNodeInABinarySearchTree_Easy{ void Main(); }
	namespace SingleNumberIII_Medium{ void Main(); }
	namespace SingleNumberII_Medium{ void Main(); }
	namespace SingleNumber_Easy{ void Main(); }
	namespace DataStreamMedian_Hard{ void Main(); }
	namespace Median_Easy{ void Main(); }
	namespace LongestCommonSubstring_Medium{ void Main(); }
	namespace LongestCommonPrefix_Medium{ void Main(); }
	namespace LongestCommonSubsequence_Medium{ void Main(); }
	namespace LongestIncreasingSubsequence_Medium{ void Main(); }
	namespace FindPeakElement_Medium{ void Main(); }
	namespace FirstBadVersion_Medium{ void Main(); }
	namespace ConstructBinaryTreefromPreorderAndInorderTraversal_Medium{ void Main(); }
	namespace ConstructBinaryTreefromInorderAndPostorderTraversal_Medium{ void Main(); }
	namespace BinaryTreeZigzagLevelOrderTraversal_Medium{ void Main(); }
	namespace BinaryTreeLevelOrderTraversalII_Medium{ void Main(); }
	namespace BinaryTreeLevelOrderTraversal_Medium{ void Main(); }
	namespace BinaryTreePostorderTraversal_Easy{ void Main(); }
	namespace BinaryTreeInorderTraversal_Easy{ void Main(); }
	namespace BinaryTreePreorderTraversal_Easy{ void Main(); }
	namespace MedianOftwoSortedArrays_Hard{ void Main(); }
	namespace MergeSortedArray_Easy{ void Main(); }
	namespace SearchInRotatedSortedArrayII_Medium{ void Main(); }
	namespace SearchInRotatedSortedArray_Medium{ void Main(); }
	namespace SearchforARange_Medium{ void Main(); }
	namespace SearchInsertPosition_Easy{ void Main(); }
	namespace ThreeSumClosest_Medium{ void Main(); }
	namespace FourSum_Medium{ void Main(); }
	namespace ThreeSum_Medium{ void Main(); }
	namespace TwoSum_Medium{ void Main(); }
	namespace CompareStrings_Easy{ void Main(); }
	namespace StringToInteger_Hard{ void Main(); }
	namespace ReverseWordsInAString_Easy{ void Main(); }
	namespace NextPermutation_Medium{ void Main(); }
	namespace PreviousPermuation_Medium{ void Main(); }
	namespace ProductOfArrayExcludeItself_Easy{ void Main(); }
	namespace SortLettersbyCase_Medium{ void Main(); }
	namespace MajorityNumberIII_Medium{ void Main(); }
	namespace MajorityNumberII_Medium{ void Main(); }
	namespace MajorityNumber_Easy{ void Main(); }
	namespace MaximumSubarrayDifference_Medium{ void Main(); }
	namespace MinimumSubarray_Easy{ void Main(); }
	namespace MaximumSubarrayIII_Hard{ void Main(); }
	namespace MaximumSubarrayII_Medium{ void Main(); }
	namespace MaximumSubarray_Easy{ void Main(); }
	namespace ImplementQueuebyTwoStacks_Medium{ void Main(); }
	namespace RecoverRotatedSortedArray_Easy{ void Main(); }
	namespace SearchATwoDMatrixII_Medium{ void Main(); }
	namespace ReverseLinkedListII_Medium{ void Main(); }
	namespace ReverseLinkedList_Easy{ void Main(); }
	namespace N_QueensII_Medium{ void Main(); }
	namespace N_Queens_Medium{ void Main(); }
	namespace MinimumWindowSubstring_Medium{ void Main(); }
	namespace PartitionArray_Medium{ void Main(); }
	namespace InsertInterval_Easy{ void Main(); }
	namespace InterleavingString_Medium{ void Main(); }
	namespace SearchATwoDMatrix_Easy{ void Main(); }
	namespace SubsetsII_Medium{ void Main(); }
	namespace Subsets_Medium{ void Main(); }
	namespace PermutationsII_Medium{ void Main(); }
	namespace Permutations_Medium{ void Main(); }
	namespace BinarySearch_Easy{ void Main(); }
	namespace strStr_Easy{ void Main(); }
	namespace MinStack_Medium{ void Main(); }
	namespace SearchRangeInBinarySearchTree_Medium{ void Main(); }
	namespace FizzBuzz_Easy{ void Main(); }
	namespace RotateString_Easy{ void Main(); }
	namespace BinaryTreeSerialization_Medium{ void Main(); }
	namespace MergeSortedArrayII_Easy{ void Main(); }
	namespace KthLargestElement_Medium{ void Main(); }
	namespace UglyNumber_Medium{ void Main(); }
	namespace DigitCounts_Medium{ void Main(); }
	namespace TrailingZeros_Easy{ void Main(); }
	namespace APlusBProblem_Medium{ void Main(); }
};
